version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.backend.staging
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dataverse
      - POSTGRES_PASSWORD=dataverse
      - POSTGRES_DB=dataverse_dev
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8080
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data:
