# Generated by Django 4.2.4 on 2023-08-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_alter_messages_text_alter_messages_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="chat_display_text",
            field=models.TextField(blank=True),
        ),
    ]
